/**
 * METER · index generator
 * ---------------------------------------------------------------------------
 * Emits `src/data/tools.generated.ts`: a lightweight, serialisable projection
 * of every CalcSpec (no `compute`, no `fields` internals) that the client uses
 * for search, cards, navigation and routing. Because it carries no calculation
 * code, importing it never drags a category's math into an unrelated bundle.
 *
 * Run with: `npm run gen`
 */

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { CATEGORIES, CATEGORY_BY_ID } from "../src/data/categories";
import { ALL_SPECS, BY_CATEGORY } from "../src/data/calculators/index";
import type { CalcMeta, CalcSpec } from "../src/lib/calc/types";

const here = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(here, "../src/data/tools.generated.ts");

const errors: string[] = [];
const KEBAB = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

function toMeta(s: CalcSpec): CalcMeta {
  const cat = CATEGORY_BY_ID[s.category];
  return {
    id: s.id,
    name: s.name,
    category: s.category,
    description: s.description,
    keywords: s.keywords,
    icon: s.icon ?? cat?.icon ?? "Calculator",
    featured: Boolean(s.featured),
    popularity: s.popularity ?? 50,
    inputs: s.fields.length,
    ...(s.custom ? { custom: s.custom } : {}),
  };
}

/* ---------------------------------------------------------------- validate */

const seen = new Set<string>();
for (const s of ALL_SPECS) {
  const tag = s.id || s.name || "?";
  if (!s.id || !KEBAB.test(s.id)) errors.push(`${tag}: id must be kebab-case`);
  if (seen.has(s.id)) errors.push(`${tag}: duplicate id`);
  seen.add(s.id);
  if (!CATEGORY_BY_ID[s.category]) errors.push(`${tag}: unknown category "${s.category}"`);
  if (!s.name?.trim()) errors.push(`${tag}: missing name`);
  if (!s.description?.trim()) errors.push(`${tag}: missing description`);
  if (!s.keywords?.length) errors.push(`${tag}: needs at least one keyword`);
  if (!s.custom && !s.fields?.length) errors.push(`${tag}: needs at least one field`);
  for (const f of s.fields ?? []) {
    if (!f.key) errors.push(`${tag}: a field is missing its key`);
    const kind = f.kind ?? "number";
    if (!f.optional && f.def === undefined && kind !== "toggle") {
      errors.push(`${tag}: field "${f.key}" must have a default (def) or be optional`);
    }
    if (kind === "select" && !f.options?.length) {
      errors.push(`${tag}: select field "${f.key}" has no options`);
    }
  }
}

if (errors.length) {
  console.error(`\n✗ gen aborted — ${errors.length} spec problem(s):`);
  for (const e of errors) console.error(`  • ${e}`);
  process.exit(1);
}

/* ------------------------------------------------------------------ emit */

const tools = ALL_SPECS.map(toMeta);
const counts = Object.fromEntries(
  CATEGORIES.map((c) => [c.id, (BY_CATEGORY[c.id] ?? []).length]),
);

const file = `// AUTO-GENERATED by scripts/gen-index.ts — do not edit by hand.
// Lightweight tool metadata (no compute code). Safe to import from any client
// bundle: search, cards, navigation, favorites and routing all read this.
import type { CalcMeta, CategoryId } from "../lib/calc/types";

export const TOTAL = ${tools.length};

export const TOOLS: CalcMeta[] = ${JSON.stringify(tools, null, 2)};

export const TOOL_BY_ID: Record<string, CalcMeta> = Object.fromEntries(
  TOOLS.map((t) => [t.id, t]),
);

export const CATEGORY_COUNTS: Record<CategoryId, number> = ${JSON.stringify(counts, null, 2)} as Record<CategoryId, number>;
`;

writeFileSync(OUT, file);

console.log(`✓ Wrote ${tools.length} tools → src/data/tools.generated.ts`);
for (const c of CATEGORIES) {
  console.log(`   ${String(counts[c.id]).padStart(3)}  ${c.name}`);
}
